export type Course = {
  id: string
  code: string
  title: string
  subtitle: string
  tier: string
  blurb: string
  description: string
  priceINR: number
  saveINR?: number
  duration: string
  sessions: number
  classSize: string
  schedule: string
  category: string
  level: string
  goal?: 'immigration' | 'certification' | 'conversation' | 'core'
  slug: string
  highlights: string[]
  abilities?: {
    eyebrow: string
    items: string[]
  }
}

export const courses: Course[] = [
  // Core levels — single
  {
    id: 'a1',
    code: 'A1',
    title: 'A1 — Absolute Beginner',
    subtitle: 'Your first steps into French. Learn survival phrases, greetings, and the foundations of the language.',
    tier: 'Beginner',
    blurb: 'First words. First compass bearing.',
    description:
      'Learn essential greetings, survival phrases, and foundational grammar. Perfect for complete beginners.',
    priceINR: 8500,
    duration: '8 weeks',
    sessions: 12,
    classSize: '4-6 students',
    schedule: 'Tue & Thu, 7–8:30 PM IST',
    category: 'Core Level',
    level: 'A1',
    goal: 'core',
    slug: 'a1-absolute-beginner',
    highlights: [
      'Essential vocabulary & greetings',
      'Basic conversations (introductions, ordering, shopping)',
      'Present tense fundamentals',
      'Pronunciation and listening skills',
      'Cultural notes on French etiquette',
    ],
    abilities: {
      eyebrow: 'WHAT YOU\'LL BE ABLE TO DO',
      items: [
        'Introduce yourself to a French colleague without freezing.',
        'Read a French menu and order confidently.',
        'Understand what someone is asking when they say "Vous parlez français ?" — and you\'ll have an answer.',
      ],
    },
  },
  {
    id: 'a2',
    code: 'A2',
    title: 'A2 — Elementary',
    subtitle: 'Express yourself with growing confidence. Handle everyday situations with ease.',
    tier: 'Beginner',
    blurb: 'Describe yourself, your life, your plans.',
    description:
      'Build on A1 foundations with more complex structures and real-world scenarios.',
    priceINR: 8500,
    duration: '8 weeks',
    sessions: 12,
    classSize: '4-6 students',
    schedule: 'Mon & Wed, 7–8:30 PM IST',
    category: 'Core Level',
    level: 'A2',
    goal: 'core',
    slug: 'a2-elementary',
    highlights: [
      'Everyday conversations & narratives',
      'Past tense & compound structures',
      'Shopping, dining, travel scenarios',
      'Listening comprehension boost',
      'French regional culture',
    ],
    abilities: {
      eyebrow: 'WHAT YOU\'LL BE ABLE TO DO',
      items: [
        'Handle a hotel check-in, ask for directions and actually understand the reply.',
        'Text a French-speaking friend about your day.',
        'No longer just memorising — you\'re communicating.',
      ],
    },
  },
  {
    id: 'b1',
    code: 'B1',
    title: 'B1 — Intermediate',
    subtitle: 'Navigate complex conversations. Handle most real-world situations independently.',
    tier: 'Intermediate',
    blurb: 'Navigate conversations. Handle most situations.',
    description:
      'Develop fluency for travel, work, and real-world interactions. The gateway to B2.',
    priceINR: 9500,
    duration: '10 weeks',
    sessions: 15,
    classSize: '4-6 students',
    schedule: 'Sat & Sun, 6–7:30 PM IST',
    category: 'Core Level',
    level: 'B1',
    goal: 'core',
    slug: 'b1-intermediate',
    highlights: [
      'True conversational fluency',
      'Subjunctive mood introduction',
      'Complex discussions & debates',
      'Workplace French basics',
      'Media comprehension',
    ],
    abilities: {
      eyebrow: 'WHAT YOU\'LL BE ABLE TO DO',
      items: [
        'Describe a problem to a doctor in France, talk about your work experience in an interview.',
        'Follow the plot of a French film without subtitles for the easy scenes.',
        'Reach the threshold for DELF B1 certification and the entry point for Canadian immigration scoring.',
      ],
    },
  },
  {
    id: 'b2',
    code: 'B2',
    title: 'B2 — Upper Intermediate',
    subtitle: 'Master nuanced expression. Reach CLB 7 for Canadian immigration pathways.',
    tier: 'Intermediate',
    blurb: 'Argue, debate, lead discussions.',
    description: 'Master nuanced expression. Reach CLB 7–8 for Canadian PR pathways.',
    priceINR: 10500,
    duration: '12 weeks',
    sessions: 18,
    classSize: '4-6 students',
    schedule: 'Tue & Thu, 6–7:30 PM IST',
    category: 'Core Level',
    level: 'B2',
    goal: 'core',
    slug: 'b2-upper-intermediate',
    highlights: [
      'Advanced grammar & nuance',
      'CLB 7 alignment',
      'Professional & academic contexts',
      'Argumentation & persuasion',
      'Literature & media analysis',
    ],
    abilities: {
      eyebrow: 'WHAT YOU\'LL BE ABLE TO DO',
      items: [
        'Argue a point in a team meeting, write a formal email to a French institution.',
        'Understand news broadcasts without rewinding.',
        'Reach the immigration and university standard, satisfying CLB 7 for Express Entry — the single most common French target for Indian professionals applying for Canadian PR.',
      ],
    },
  },

  // Combined tracks
  {
    id: 'a1-a2',
    code: 'A1+A2',
    title: 'A1+A2 Track',
    subtitle: 'Zero to conversational in one accelerated journey.',
    tier: 'Beginner',
    blurb: 'Jump-start your journey: zero to conversational in 16 weeks.',
    description:
      'Accelerated pathway combining A1 and A2 with integrated practice.',
    priceINR: 15200,
    saveINR: 1800,
    duration: '16 weeks',
    sessions: 24,
    classSize: '4-6 students',
    schedule: 'Flexible (multiple options)',
    category: 'Combined Track',
    level: 'A1–A2',
    goal: 'core',
    slug: 'a1-a2-track',
    highlights: ['20% savings', 'Cohesive curriculum', 'Fluent intro level'],
    abilities: {
      eyebrow: 'WHY THE COMBINED TRACK',
      items: [
        'No restart, no repetition, no gap.',
        'Move from your first French word to practical everyday communication in one continuous program.',
        'Perfect if you have a target date for an exam, a move, or a job that requires French.',
      ],
    },
  },
  {
    id: 'a2-b1',
    code: 'A2+B1',
    title: 'A2+B1 Track',
    subtitle: 'Bridge to true intermediate fluency.',
    tier: 'Beginner–Intermediate',
    blurb: 'Bridge the gap. Elementary to true intermediate.',
    description:
      'Seamless progression with continuous practice and real-world scenarios.',
    priceINR: 17500,
    saveINR: 2500,
    duration: '18 weeks',
    sessions: 21,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Combined Track',
    level: 'A2–B1',
    goal: 'core',
    slug: 'a2-b1-track',
    highlights: ['15% savings', 'Integrated project', 'Travel ready'],
    abilities: {
      eyebrow: 'WHY THE COMBINED TRACK',
      items: [
        'Built for learners who are past the basics but not yet independent.',
        'Close the gap between "I understand a little" and "I can actually handle this situation".',
        'Do it without breaking momentum between levels.',
      ],
    },
  },
  {
    id: 'b1-b2',
    code: 'B1+B2',
    title: 'B1+B2 Track',
    subtitle: 'Master fluency and exam readiness.',
    tier: 'Intermediate',
    blurb: 'Reach fluency. B1 to B2 mastery.',
    description: 'Intensive path to upper-intermediate fluency and exam readiness.',
    priceINR: 19500,
    saveINR: 2500,
    duration: '22 weeks',
    sessions: 27,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Combined Track',
    level: 'B1–B2',
    goal: 'core',
    slug: 'b1-b2-track',
    highlights: ['13% savings', 'Exam prep foundation', 'Professional level'],
    abilities: {
      eyebrow: 'WHY THE COMBINED TRACK',
      items: [
        'The B1→B2 jump is where most learners stall.',
        'Designed specifically to carry you through it — building the argumentative and professional French that B2 demands while B1 is still fresh.',
        'Strong choice for anyone with an immigration or DELF B2 deadline.',
      ],
    },
  },
  {
    id: 'a2-b1-b2',
    code: 'A2+B1+B2',
    title: 'A2+B1+B2 Master Track',
    subtitle: 'The complete intermediate journey.',
    tier: 'Complete Intermediate',
    blurb: 'The full intermediate journey in one cohesive curriculum.',
    description: 'Expert-paced progression from post-beginner to upper-intermediate.',
    priceINR: 26500,
    saveINR: 4400,
    duration: '30 weeks',
    sessions: 45,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Combined Track',
    level: 'A2–B2',
    goal: 'core',
    slug: 'a2-b1-b2-track',
    highlights: ['17% savings', 'Integrated projects', 'CLB 7+ ready'],
    abilities: {
      eyebrow: 'WHY THE COMBINED TRACK',
      items: [
        'This is the full sprint: from functional communication to exam-ready upper-intermediate French.',
        'One structured program without switching schools or losing continuity.',
        'Chosen by learners who have a firm goal — Canadian PR, a university requirement, a job in a French-speaking country.',
      ],
    },
  },

  // Exam prep
  {
    id: 'tef-prep',
    code: 'TEF',
    title: 'TEF Preparation',
    subtitle: 'Master exam strategies and ace the test.',
    tier: 'Exam Prep',
    blurb: 'Master TEF Compréhension & Expression strategies.',
    description: 'Targeted exam strategy, timed drills, and score prediction.',
    priceINR: 7500,
    duration: '6 weeks',
    sessions: 9,
    classSize: '4-6 students',
    schedule: 'Sat & Sun',
    category: 'Exam Prep',
    level: 'B2–C1',
    goal: 'certification',
    slug: 'tef-preparation',
    highlights: [
      'Exam format deep-dive',
      'Time management',
      'Score prediction',
    ],
    abilities: {
      eyebrow: 'WHAT THIS COURSE IS ACTUALLY FOR',
      items: [
        'The TEF Canada exam is the gateway to Express Entry points and Canadian citizenship.',
        'Not general French revision — targeted, scored, and strategy-driven.',
        'Practice every component under timed conditions, learn how CLB scoring maps to your target, go into exam day knowing exactly what the examiners want.',
      ],
    },
  },
  {
    id: 'tcf-prep',
    code: 'TCF',
    title: 'TCF Speaking & Writing',
    subtitle: 'Master productive skills for Canadian Express Entry.',
    tier: 'Exam Prep',
    blurb: 'TCF Expression orale & Expression écrite mastery.',
    description:
      'Focus on the productive skills for Canadian Express Entry and institutional placement.',
    priceINR: 7500,
    duration: '6 weeks',
    sessions: 9,
    classSize: '4-6 students',
    schedule: 'Sat & Sun',
    category: 'Exam Prep',
    level: 'B2–C1',
    goal: 'certification',
    slug: 'tcf-speaking-writing',
    highlights: [
      'Speaking fluency drills',
      'Writing clarity',
      'Real exam conditions',
    ],
    abilities: {
      eyebrow: 'WHAT THIS COURSE IS ACTUALLY FOR',
      items: [
        'Most TCF candidates lose marks not because they don\'t know French — but because they don\'t know how to structure a spoken response or a written argument under pressure.',
        'This course fixes that: pure speaking and writing practice with task-specific feedback, timed drills, and the examiner\'s marking criteria built into every session.',
      ],
    },
  },
  {
    id: 'b2-tef-combo',
    code: 'B2+TEF',
    title: 'B2 + TEF Combo',
    subtitle: 'B2 fluency plus TEF exam mastery.',
    tier: 'Exam Prep',
    blurb: 'Reach B2, then ace the TEF.',
    description: 'Complete B2 level + specialized exam prep in one package.',
    priceINR: 17500,
    saveINR: 2500,
    duration: '18 weeks',
    sessions: 21,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Exam Prep',
    level: 'B1–B2 + TEF',
    goal: 'certification',
    slug: 'b2-tef-combo',
    highlights: ['15% savings', 'Pathway to CLB 9', 'Integrated strategy'],
    abilities: {
      eyebrow: 'WHY THIS COMBINATION WORKS',
      items: [
        'Most TEF coaching assumes you\'re already at B2.',
        'This course builds the level and the exam skill together.',
        'Not paying for two courses at different times, and not attempting the TEF before you\'re ready — one program, one instructor thread, one target outcome.',
      ],
    },
  },

  // Masterclasses
  {
    id: 'dalf-c1',
    code: 'DALF C1',
    title: 'DALF C1 Masterclass',
    subtitle: 'Advanced nuance and sophisticated expression.',
    tier: 'Advanced',
    blurb: 'Nuance, precision, authentic fluency.',
    description:
      'Advanced expression, argumentation, and sophisticated listening comprehension.',
    priceINR: 14000,
    duration: '10 weeks',
    sessions: 15,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Masterclass',
    level: 'C1',
    goal: 'certification',
    slug: 'dalf-c1-masterclass',
    highlights: [
      'Advanced argumentation',
      'DALF exam format',
      'Authentic materials',
    ],
    abilities: {
      eyebrow: 'WHAT THIS MASTERCLASS IS ACTUALLY FOR',
      items: [
        'DALF C1 is required by many French universities for postgraduate admission and by some employers for senior roles in French-speaking organisations.',
        'The exam tests near-native command — nuanced reading, complex writing, sustained oral argument.',
        'This masterclass covers exam strategy and component-by-component practice for candidates who already have strong French and need to perform at the highest level.',
      ],
    },
  },
  {
    id: 'dalf-c2',
    code: 'DALF C2',
    title: 'DALF C2 Masterclass',
    subtitle: 'Native-level sophistication and mastery.',
    tier: 'Mastery',
    blurb: 'The summit. Native-level sophistication.',
    description: 'Master near-native-speaker fluency, subtlety, and style.',
    priceINR: 14000,
    duration: '10 weeks',
    sessions: 15,
    classSize: '4-6 students',
    schedule: 'Flexible',
    category: 'Masterclass',
    level: 'C2',
    goal: 'certification',
    slug: 'dalf-c2-masterclass',
    highlights: [
      'Near-native nuance',
      'Literary analysis',
      'DALF C2 format',
    ],
    abilities: {
      eyebrow: 'WHAT THIS MASTERCLASS IS ACTUALLY FOR',
      items: [
        'C2 is the summit — the only French certification that signals complete mastery.',
        'Few candidates pursue it, and those who do are typically aiming for academic careers, translation work, or roles where French is the primary professional language.',
        'This masterclass prepares you for the most demanding exam in the CEFR framework, component by component.',
      ],
    },
  },

  // Workshops
  {
    id: 'conversation-workshop',
    code: 'Ateliers',
    title: 'French Conversation Workshop',
    subtitle: 'Unscripted practice with peers.',
    tier: 'Workshop',
    blurb: 'Unscripted conversation practice with peers.',
    description: 'Low-pressure group practice for all levels. Drop in anytime.',
    priceINR: 3500,
    duration: '4 weeks (ongoing)',
    sessions: 8,
    classSize: '6-8 students',
    schedule: 'Weekly',
    category: 'Workshop',
    level: 'A2–C2',
    goal: 'conversation',
    slug: 'conversation-workshop',
    highlights: [
      'Peer practice',
      'No scripts',
      'Cultural immersion',
    ],
    abilities: {
      eyebrow: 'WHAT THIS WORKSHOP IS ACTUALLY FOR',
      items: [
        'This is not a grammar class.',
        'For learners who understand French reasonably well but go quiet the moment they have to speak.',
        'Built around real dialogue — the kind that happens at work, at a dinner table, on a phone call — with pronunciation correction and live feedback that grammar drills can\'t give you.',
      ],
    },
  },

  // E-books
  {
    id: 'ebook-a1',
    code: 'A1',
    title: 'A1 Vocabulary E-Book',
    subtitle: '500 essential words for beginners.',
    tier: 'Resource',
    blurb: '500 essential words with example sentences.',
    description: 'Downloadable PDF with audio pronunciation guide.',
    priceINR: 599,
    duration: 'Instant download',
    sessions: 1,
    classSize: 'Self-study',
    schedule: 'Anytime',
    category: 'E-Book',
    level: 'A1',
    goal: 'conversation',
    slug: 'ebook-a1-vocabulary',
    highlights: ['500+ words', 'Audio guide', 'Printable'],
    abilities: {
      eyebrow: 'WHAT THIS GETS YOU',
      items: [
        'A structured vocabulary reference built specifically for French Compass students.',
        'Not random word lists — themed sets organised by topic, with example sentences.',
        'Shows the word in the kind of context you\'ll actually encounter in class and in the exam. A supplement to your course, not a replacement for it.',
      ],
    },
  },
  {
    id: 'ebook-a2',
    code: 'A2',
    title: 'A2 Vocabulary E-Book',
    subtitle: '750 practical words for A2 learners.',
    tier: 'Resource',
    blurb: '750 practical words for A2 learners.',
    description: 'Comprehensive vocabulary reference with context and usage.',
    priceINR: 599,
    duration: 'Instant download',
    sessions: 1,
    classSize: 'Self-study',
    schedule: 'Anytime',
    category: 'E-Book',
    level: 'A2',
    goal: 'conversation',
    slug: 'ebook-a2-vocabulary',
    highlights: ['750+ words', 'Usage examples', 'Mobile-friendly'],
    abilities: {
      eyebrow: 'WHAT THIS GETS YOU',
      items: [
        'A structured vocabulary reference built specifically for French Compass students.',
        'Not random word lists — themed sets organised by topic, with example sentences.',
        'Shows the word in the kind of context you\'ll actually encounter in class and in the exam. A supplement to your course, not a replacement for it.',
      ],
    },
  },
  {
    id: 'ebook-b1',
    code: 'B1',
    title: 'B1 Vocabulary E-Book',
    subtitle: '1,200 words for intermediate learners.',
    tier: 'Resource',
    blurb: '1,200 words spanning business, culture, and current events.',
    description: 'Advanced vocabulary reference with nuance and register.',
    priceINR: 1199,
    duration: 'Instant download',
    sessions: 1,
    classSize: 'Self-study',
    schedule: 'Anytime',
    category: 'E-Book',
    level: 'B1',
    goal: 'conversation',
    slug: 'ebook-b1-vocabulary',
    highlights: ['1,200+ words', 'Register guide', 'Topic index'],
    abilities: {
      eyebrow: 'WHAT THIS GETS YOU',
      items: [
        'A structured vocabulary reference built specifically for French Compass students.',
        'Not random word lists — themed sets organised by topic, with example sentences.',
        'Shows the word in the kind of context you\'ll actually encounter in class and in the exam. A supplement to your course, not a replacement for it.',
      ],
    },
  },
  {
    id: 'ebook-b2',
    code: 'B2',
    title: 'B2 Vocabulary E-Book',
    subtitle: '1,500 sophisticated words for fluency.',
    tier: 'Resource',
    blurb: '1,500 sophisticated words for near-fluency.',
    description:
      'Mastery-level vocabulary covering idioms, formal register, and specialized fields.',
    priceINR: 1199,
    duration: 'Instant download',
    sessions: 1,
    classSize: 'Self-study',
    schedule: 'Anytime',
    category: 'E-Book',
    level: 'B2',
    goal: 'conversation',
    slug: 'ebook-b2-vocabulary',
    highlights: ['1,500+ words', 'Idioms included', 'Audio pronunciation'],
    abilities: {
      eyebrow: 'WHAT THIS GETS YOU',
      items: [
        'A structured vocabulary reference built specifically for French Compass students.',
        'Not random word lists — themed sets organised by topic, with example sentences.',
        'Shows the word in the kind of context you\'ll actually encounter in class and in the exam. A supplement to your course, not a replacement for it.',
      ],
    },
  },
]

export const coursesByLevel = {
  core: courses.filter((c) => c.goal === 'core'),
  certification: courses.filter((c) => c.goal === 'certification'),
  conversation: courses.filter((c) => c.goal === 'conversation'),
}
